version: "3"

services:
  elzabet:
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        app_port: 3000
      #   app_db: app-db:30000
      #   app_env: alpha
    command: npm start
    container_name: elzabet
    restart: always
    volumes:
      - ./src:/app/server/src
    ports:
      - 3000:3000
    links:
      - db
  db:
    container_name: elzabet-mysql
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'test'
      MYSQL_ROOT_PASSWORD: 'test'
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: